### ISSUE TITLE
InvalidCastException : AsmResolver.Net

### ISSUE THREAD

**Issue by Sayness** [Washi1337/OldRod#11]
when I put the software obfuscate with koivm it makes me an erreur has "Excuting CIL Recompiler Stage ..."

Download Link of the software : https://www.dropbox.com/s/31kj7fc2qbok491/software.zip?dl=0

Error : Can not cast an object of type 'AsmResolver.Net.Signatures.TypeDefOrRefSignature' to type 'AsmResolver.Net.Signatures.ByReferenceTypeSignature'.

Screenshot of the error : https://i.imgur.com/Et683bU.png

**Comment by MauriceHuber** [comment]
This is identical to Issue #6 
It has been resolved in the last update yesterday.

**Comment by MauriceHuber** [comment]
Download the latest version [HERE](https://ci.appveyor.com/project/Washi1337/OldRod/branch/master/artifacts)

**Comment by Sayness** [comment]
even with the latest update this makes me the mistake

**Comment by MauriceHuber** [comment]
I just checked again, it doesn't work for me aswell, in the meanwhile just use `--salvage`.

**Comment by Sayness** [comment]
with "--salvage" error : [Recompile]: Failed to recompile function_EAB7. Can not cast an object of type 'AsmResolver.Net.Signatures.TypeDefOrRefSignature' to type 'AsmResolver.Net.Signatures.ByReferenceTypeSignature'.

**Comment by MauriceHuber** [comment]
It will still give the error, but it will compile the exe successfullly so you can look at the code.

**Comment by Sayness** [comment]
it works, thanks ^^

**Comment by MauriceHuber** [comment]
No problem, but still wait for Washi to fix the issue.

**Comment by Washi1337** [comment]
While similar, the actual cause was different. Thanks for the report.

This bug seems to pop up every now and then. I changed the error slightly to a more meaningful message.
