### ISSUE TITLE
Option that overrides constants

### ISSUE THREAD

**Issue by TobitoFatitoNulled** [Washi1337/OldRod#12]
**Is your feature request related to a problem? Please describe.**
People starting to find out that you can scramble the mdtokens of constants, making the tool useless. I'd love to see a feature added to override the constant values if possible :)

**Describe the solution you'd like**
--constants-override "file (json or txt)", which will override the constant (for example: 0:15 means REG_R0 has a value of 15)

**Comment by Washi1337** [comment]
I added support for user-defined constants. Check [doc/example-config.json](https://github.com/Washi1337/OldRod/blob/master/doc/example-config.json). Use `--config file.json`.

Let me know if you miss anything or like something changed.

**Comment by TobitoFatitoNulled** [comment]
Perfect, thank you :)
