### ISSUE TITLE
Something went wrong! i cant use with oldrod look on report 

### ISSUE THREAD

**Issue by Samui11** [Washi1337/OldRod#23]
**Describe the bug**
every time i drag to oldrod some protect file its do that i think i have some bugs 

maby i just idiot but help me please 

[report.log](https://github.com/Washi1337/OldRod/files/4000325/report.log)

**Comment by Washi1337** [comment]
Hi,

The error in the log should be clear enough:
```
  ERROR: 13:08:50.906 [TUI]: OldRod.Pipeline.DevirtualisationException: Koi stream was not found in the target PE. This could be because the input file is not protected with KoiVM, or the metadata stream uses a name that is different from the one specified in the input parameters.
```

You have to tell OldRod the new name of the koi stream (using e.g. the `--koi-stream-name` commandline argument).

Best regards,

**Comment by Samui11** [comment]
Hi, thanks so much,
i fucking idiot i put the file in de4dot that dont work becuse that! 
Thanks alot !
