### ISSUE TITLE
No OldRod Executable to be Found

### ISSUE THREAD

**Issue by JustMaaarc** [Washi1337/OldRod#27]
I've redownloaded the Newest Version of OldRod-master now and I just simply can't find any Executable or (Drag and Drop) file that I can use.

Screenshot: https://imgur.com/a/gqSff0F

**Comment by Washi1337** [comment]
You downloaded source code.  You need to build it using e.g. Visual Studio, JetBrains Rider or just simply use MSBuild.

**Comment by JustMaaarc** [comment]
Sorry for being an extra noob but can you paste me the Full command I'd need to build the exe via cmd (if that's where you use MSBuild)

**Comment by Washi1337** [comment]
Simply use:
```
msbuild
```
while being in the `src` directory.

Alternatively, you can download the bleeding-edge artifacts from [AppVeyor](https://ci.appveyor.com/project/Washi1337/OldRod/branch/master/artifacts).

**Comment by Washi1337** [comment]
Closed for inactivity.
