### ISSUE TITLE
error "Recompilation of vcall CKOVERFLOW is not supported"

### ISSUE THREAD

**Issue by reverser69** [Washi1337/OldRod#28]
didn't know if its really not supported or a bug so I'm sending the file. it's just a crap exe packed for a challenge.
is it possible to manually fix these?! or just skip this not-supported part so i can look into the devirted exe?
file:
https://easyupload.io/4ofp7o

**Comment by Washi1337** [comment]
Duplicate of #4 
CKOVERFLOW is not supported at the moment. You can try enabling `--salvage` to ignore any errors.
