### ISSUE TITLE
Reassembling File: System.InvalidOperationException

### ISSUE THREAD

**Issue by scouteh** [Washi1337/OldRod#29]
Bug:
I don't know how I could say it. But happens when it tries to reassemble the file.

**To Reproduce**
Drag and drop the sample in OldRod and you will get the error.
Sample: https://anonymousfiles.io/jhsrh9Sr/

**Expected behavior**
I expected it to devirtualize it succesfully, because I had a sample that looked same and it got succesfully devirtualized.

**Screenshots**
![image](https://user-images.githubusercontent.com/60182984/77215129-3672be80-6b1b-11ea-91e2-06e2a131bfbc.png)

report file:
[report.log](https://github.com/Washi1337/OldRod/files/4362200/report.log)

**Comment by Washi1337** [comment]
Hi, 

Your sample binary is a 64-bit .NET assembly. Unfortunately, AsmResolver v3, the metadata back-end of OldRod, is not able to build 64-bit .NET assemblies ( Washi1337/AsmResolver#21 ). Note that there's a new version of AsmResolver in the works that does support it.

Seems like there's some demand for it though, I will see if I can make some time for it to make AsmResolver v3 support writing 64-bit assemblies.

Regards

**Comment by Washi1337** [comment]
Should no longer happen now. Let me know if you encounter any other issues.
