### ISSUE TITLE
Something went wrong! Try the latest version or report a bug at the repository

### ISSUE THREAD

**Issue by KermitThefrog13** [Washi1337/OldRod#31]
pls help i don't know how to update it im new here :((

**Comment by Washi1337** [comment]
I can't help you if you don't provide any information on what went wrong.

**Comment by KermitThefrog13** [comment]
hmm but can you help me how to install the latest version im a noob :((

**Comment by Washi1337** [comment]
Downloading the latest version can be done by cloning the repository and building it in Visual Studio, JetBrains Rider or simply use MSBuild. You can also download the latest builds at [the build server hosted by AppVeyor](https://ci.appveyor.com/project/Washi1337/oldrod/build/artifacts).

To narrow down exactly what is happening, I still need more information.
Please refer to: https://github.com/Washi1337/OldRod#heeeeeelp-it

**Comment by KermitThefrog13** [comment]
There was an error while trying to complete the current operation. Please contact AppVeyor support.
??? the heck is that

**Comment by Washi1337** [comment]
I still have no way to reproduce your bug.

> Please contact AppVeyor support.

If you're having problems with AppVeyor, this sounds like the thing you should do next. I cannot solve AppVeyor specific problems.

**Comment by KermitThefrog13** [comment]
INFO: 22:13:48.374 [Main]: Started devirtualisation.
   INFO: 22:13:48.380 [Main]: Opening target file C:\Users\JenzenAclan\Desktop\MyHackingFolder\Cracker\MinecraftChecker\MinecraftCheckerProtected.exe...
  DEBUG: 22:13:48.456 [Main]: Attempting to autodetect location of the runtime library...
  DEBUG: 22:13:48.456 [Main]: No references found to a runtime library.
   INFO: 22:13:48.458 [Main]: Runtime is embedded in the target assembly.
   INFO: 22:13:48.460 [Main]: Executing Constants resolution stage...
  DEBUG: 22:13:48.461 [ConstantsResolver]: Attempting to auto-detect constants...
  DEBUG: 22:13:48.472 [ConstantsResolver]: Locating constants type...
  ERROR: 22:13:48.500 [TUI]: OldRod.Pipeline.DevirtualisationException: Could not locate constants type!
   at OldRod.Pipeline.Stages.ConstantsResolution.ConstantsResolutionStage.FindConstantFieldsAndValues(DevirtualisationContext context)
   at OldRod.Pipeline.Stages.ConstantsResolution.ConstantsResolutionStage.AutoDetectConstants(DevirtualisationContext context)
   at OldRod.Pipeline.Stages.ConstantsResolution.ConstantsResolutionStage.Run(DevirtualisationContext context)
   at OldRod.Pipeline.Devirtualiser.RunPipeline(DevirtualisationContext context)
   at OldRod.Pipeline.Devirtualiser.Devirtualise(DevirtualisationOptions options)
   at OldRod.Program.Main(String[] args)
   INFO: 22:13:48.503 [TUI]: Process finished with 0 warnings and 1 errors.
???

**Comment by Washi1337** [comment]
It seems oldrod cannot autodetect some crucial information about the configuration of the applied virtualization in your sample. Couple of reasons this could happen:

- Your binary is not protected by KoiVM
- Your binary is protected by a modified version of KoiVM
- Old rod contains a bug.

I cannot answer this question until you provide me a repro.
 
You could also try specifying the constants type explicitly using the `--constants-type` command line argument.
