### ISSUE TITLE
Error ExceptionHandler

### ISSUE THREAD

**Issue by SuperPower28** [Washi1337/OldRod#32]
Hey i'am boomer and i post issue because i have bug when i drag and drop the file, i have debug and i get the error here 

https://zupimages.net/viewer.php?id=20/16/dgh4.png

**Comment by Washi1337** [comment]
Seems like a duplicate of #17 with exception handlers. Try `--salvage` to ignore the error.

Nonetheless, a sample binary would be appreciated.
