### ISSUE TITLE
[Question] Detect any virtualization ?

### ISSUE THREAD

**Issue by graysuit** [Washi1337/OldRod#34]
Sir,
How do I detect any VM or virtualization software ?
Your respo is something alternative to VMprotect,

Here is the question on stackoverflow:
Mostly are based on software manufacturer name,
They just compare manufacturer name and return results,
And other one won't work,
See proof,
https://stackoverflow.com/questions/154163/detect-virtualized-os-from-an-application

What will be proper way to detect virtualization,
So that I may detect all VMs,
What will your advice.
I am programmer So,
You can provide me any language code that works for windows only (C#/VB/C/Java etc),
Thanks for reading.

**Comment by Washi1337** [comment]
Closing as this is not related to OldRod in any shape or form.

**Comment by graysuit** [comment]
100% it is not related,
It is just question,
I will be happy if you answer,
Thanks
