### ISSUE TITLE
Recompiler uses ldsfld for instance fields

### ISSUE THREAD

**Issue by ElektroKill** [Washi1337/OldRod#35]
**Describe the bug**
The recompiler uses the ldsfld opcode which is meant for static fields to load instance fields. The proper ldfld should be used.

**To Reproduce**
My KeyGenMe (Washi you have the link I am pretty sure)

**Expected behavior**
The ldfld opcode is used for instance fields while the ldsfld opcode is used for static fields

**Comment by Washi1337** [comment]
Implemented in 4416a591e533a0ef4566d3b907dbce99b2834b05
