### ISSUE TITLE
Koivm Mod Error

### ISSUE THREAD

**Issue by Cox-6** [Washi1337/OldRod#40]
**Describe the bug**
Error: InvalidCastException: Unable to cast object of type 'AsmResolver.DotNet.Serialized.SerializedMethodDefinition' to type 'AsmResolver.DotNet.TypeDefinition'.
Attached is bug report.
This is a modded koivm, I used the settings: "OldRod.exe C:\Users\Cox\Downloads\KIR-BENI-DELUXE.exe -kd C:\Users\Cox\Downloads\gay.bin --entry-type 06000064 --salvage". 
gay.bin = dumped koi variable number 1
[report.log](https://github.com/Washi1337/OldRod/files/6556018/report.log)

**To Reproduce**
Reproduce: https://cdn.discordapp.com/attachments/829711167719079945/847527939377201232/KIR-BENI-DELUXE.exe
**Expected behavior**
I expected it to work.

**Screenshots**

**Additional context**
I think this is a bug.

**Comment by Washi1337** [comment]
That being said. You are miss-using the `--entry-type` commandline argument. This command line argument expects a token for a type and not a method. This explains the exception that you are getting.

Important to remember is that OldRod has limited support for modifications out of the box. Please read [this](https://github.com/Washi1337/OldRod#will-old-rod-support-modifications-of-koivm) for more information.

**Comment by Washi1337** [comment]
Closed for inactivity.
