### ISSUE TITLE
`Neg` OpCode is not supported.

### ISSUE THREAD

**Issue by ElektroKill** [Washi1337/OldRod#46]
**Describe the bug**
KoiVM converts the CIL `Neg` OpCode into two different expressions depending on the type.
* For R4 and R8 values it emits `0 - a` in place of `-a`
* For all other values it emits `~a + 1` in place of `-a`

**To Reproduce**
Devirtualize sample file provided for issue #44.

**Expected behavior**
The `Neg` OpCode should be emitted for both of the aforementioned expressions.

**Screenshots**
Example of 'obfuscated' `Neg`:
![image](https://user-images.githubusercontent.com/37494960/149657051-31639ca6-5df2-4d5c-a906-b1d9839d6e7e.png)

**Comment by Washi1337** [comment]
Note: This is most likely supposed to be done on IL Ast level, as it is just a special case of the normal `a - b` operation:

https://github.com/Washi1337/OldRod/blob/6773f8dcc780efae20722fe3242d7afc6144d564/src/OldRod.Core/Ast/IL/Transform/LogicSimplifier.cs#L104

**Comment by Washi1337** [comment]
By the way, the provided sample does not have a test case for R4 and R8. Could you maybe upload one?

**Comment by ElektroKill** [comment]
Sure, here is a new version of the original sample which includes two new additional methods with test cases for R4 and R8.
[sample-new.zip](https://github.com/Washi1337/OldRod/files/7891182/sample-new.zip)
