### ISSUE TITLE
NotSupportedException: Invalid or unsupported method body header

### ISSUE THREAD

**Issue by hypedcarts** [Washi1337/OldRod#5]
Please look at the screenshot.

https://ibb.co/vhvwMKN

**Comment by Washi1337** [comment]
Thanks for the report, however this does not look like a bug that is within the scope of Old Rod. Make sure that method bodies in the target assembly are well formed and not encrypted by an obfuscator.

If this is not applicable to this case, then I might need further information, and potentially a sample binary.
