### ISSUE TITLE
Latest Build Artifacts Missing

### ISSUE THREAD

**Issue by int3grate** [Washi1337/OldRod#58]
Looks like the latest build artifacts were automatically deleted after a month.  Anyway to trigger a rebuild?  Thanks!

**Comment by Washi1337** [comment]
Just issued a new build. 

Building should not be too difficult. In case the builds expire again, just clone the repository and run `dotnet`, e.g.:
```
git clone --recursive https://github.com/Washi1337/OldRod
cd OldRod
dotnet build
```
