### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gagmeng** [Washi1337/OldRod#60]
![image](https://user-images.githubusercontent.com/13564117/178459102-913ef95a-63f7-44c3-b3e3-aa8aebda5bff.png)

**Comment by Washi1337** [comment]
Please make sure you have the latest C# compiler installed (available through the dotnet SDK)

**Comment by gagmeng** [comment]
> Please make sure you have the latest C# compiler installed (available through the dotnet SDK)

![image](https://user-images.githubusercontent.com/13564117/178622557-3c02b2cc-7c97-4554-b3f5-a6429272ebb4.png)
I have installed many versions of SDK or runtime, but I don't know which version should I install correctly. Thanks

**Comment by Washi1337** [comment]
For these patterns you need to use C# 8.0 or later. Your .NET SDK 6.0 installation should come with this. Make sure that your IDE actually uses it. Otherwise, simply run use
```
dotnet build
```
in the root folder, using the `dotnet.exe` from your .NET SDK 6.0 installation.
