### ISSUE TITLE
AssemblyResolutionException: Assembly mscorlib, Version=2.0.0.0, 

### ISSUE THREAD

**Issue by Outbuilt** [Washi1337/OldRod#7]
19:26:44.188 [Main]: Started devirtualisation.
19:26:44.196 [Main]: Opening target file D:\!Important\repos\ConsoleApp5\ConsoleApp5\bin\Debug\Confused\ConsoleApp5.exe...
19:26:44.278 [Main]: Runtime is embedded in the target assembly.
19:26:44.279 [Main]: Executing Constants resolution stage...
19:26:44.341 [Main]: Executing #Koi stream parsing stage...
19:26:44.342 [Main]: Executing Virtualised method detection stage...
19:26:44.385 [Main]: Executing OpCode mapping resolution stage...
19:26:44.403 [Main]: Executing VM code recovery stage...
19:26:44.537 [Main]: Executing Code Analysis Stage...
19:26:44.627 [Main]: Executing IL AST builder stage...
19:26:44.721 [Main]: Executing CIL Recompiler stage...
19:26:45.070 [Main]: Executing Clean up stage...
19:26:45.071 [Main]: Commiting changes to metadata streams...
19:26:45.150 [TUI]: Something went wrong! Try the latest version or report a bug at the repository.
19:26:45.151 [TUI]: AssemblyResolutionException: Assembly mscorlib, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 could not be resolved.
19:26:45.151 [TUI]: Use --verbose or inspect the full report.log using --log-file for more details.
19:26:45.152 [TUI]: Process finished with 0 warnings and 1 errors.
https://outbuilt.ooo/o/y1ocp.png

**Comment by Washi1337** [comment]
Thanks for the report. This might actually not be an issue related to oldrod, but to the backend asmresolver. Is it possible to get a sample binary or a description of how to reproduce this issue? Otherwise can you provide the report.log that is generated when using --log-file ? This will speed up the process of finding the issue.

**Comment by Outbuilt** [comment]
Here is the report log: https://outbuilt.ooo/o/lylqr.log

**Comment by Washi1337** [comment]
Make sure that you have .NET framework 2.0 installed in order to process .NET framework 2.0 files. 

If this is the case, I probably will need the binary that causes the problem.

**Comment by Washi1337** [comment]
Any update on a sample binary or description on how to reproduce? If not, then I'll close this.
