### ISSUE TITLE
[Add] --custom-sig

### ISSUE THREAD

**Issue by TobitoFatitoNulled** [Washi1337/OldRod#8]
The 'fish' signature (1752394086u) can be modified. I'd love to see support for that if possible :)

**Comment by Washi1337** [comment]
This should be handled fine. A "fish" signature miss-match is only producing a warning not an error:
https://github.com/Washi1337/OldRod/blob/master/src/OldRod.Core/Architecture/KoiStream.cs#L42

**Comment by TobitoFatitoNulled** [comment]
My bad, i thought it stopped the parsing.
